---

- hosts: all
  become: true
  tasks:


  - name: install apache and php for Mint servers
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Linux Mint"


- name: install apache and php for Fedora servers
    dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Fedora"

