---

- hosts: all
  become: true
  tasks:


  - name: install updates (Fedora)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Fedora"

  - name: install updates (Linux Mint)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Linux Mint"


- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php for Mint servers
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Linux Mint"


  - name: install apache and php for Fedora servers
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Fedora"

